name: instaclone
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
#  GetX
  get: ^4.6.6
#  Media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  eva_icons_flutter: ^3.1.0
#  Services
  logger: ^2.5.0
  fluttertoast: ^8.2.10
  shared_preferences: ^2.4.0
#  Networking
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

